### ISSUE TITLE
Timestamp is required

### ISSUE THREAD

**Issue by dtivel** [onovotny/NuGetKeyVaultSignTool#122]
Passing a `null` timestamp service URL will cause an exception [here](https://github.com/novotnyllc/NuGetKeyVaultSignTool/blob/946e5c863a12a65feceecce50840dc611d9d1da8/NuGetKeyVaultSignTool.Core/SignCommand.cs#L64).  Also, [KeyVaultSignatureProvider requires a timestamp provider.](https://github.com/novotnyllc/NuGetKeyVaultSignTool/blob/946e5c863a12a65feceecce50840dc611d9d1da8/NuGetKeyVaultSignTool.Core/KeyVaultSignatureProvider.cs#L28)

**Comment by clairernovotny** [comment]
This is by design and won't be fixed. Timestamps are required....
