### ISSUE TITLE
Microsoft.Extensions.CommandLineUtils not found

### ISSUE THREAD

**Issue by prochan2** [onovotny/NuGetKeyVaultSignTool#8]
Following the tutorial in readme.md, I get the following error as the only output of the NuGetKeyVaultSignTool.exe command:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at NuGetKeyVaultSignTool.Program.Main(String[] args)

The version installed is 1.2.3.

I've built the tool myself as a work-around.

**Comment by onovotny** [comment]
That's very strange it that it missed the file in the publish.

**Comment by tistocks** [comment]
It looks like the package has no files except the NuGetKeyVaultSignTool.exe.  Looking at the project file there seems to be other tools missing.  Can we get a rebuild of the package or at the very least is there an older version that can be pulled that we can use to get unblocked?

**Comment by onovotny** [comment]
1.2.18 has this fix in it: https://www.nuget.org/packages/NuGetKeyVaultSignTool/1.2.18
